-- Independent official full-price catalog for the GearDrop Yearbook.
-- Deals tables (products and price_history) are intentionally untouched.

create table if not exists public.catalog_products (
  catalog_product_id text primary key
    check (catalog_product_id ~ '^(arcteryx|burton|patagonia):[a-z0-9][a-z0-9._-]{1,63}$'),
  brand_key text not null
    check (brand_key in ('arcteryx', 'burton', 'patagonia')),
  official_product_id text not null
    check (official_product_id ~ '^[0-9A-Z][0-9A-Z._-]{1,63}$'),
  brand text not null,
  catalog_scope text not null default 'full_price'
    check (catalog_scope = 'full_price'),
  market text not null check (pg_catalog.btrim(market) <> ''),
  country text not null check (country ~ '^[a-z]{2}$'),
  language text not null default 'en' check (language = 'en'),
  name text not null check (pg_catalog.btrim(name) <> ''),
  gender text not null check (gender in ('men', 'women', 'kids', 'unisex')),
  collection text,
  categories text[] not null default '{}',
  category_sources jsonb not null default '{}'
    check (pg_catalog.jsonb_typeof(category_sources) = 'object'),
  list_price numeric(12, 2) not null check (list_price >= 0),
  list_price_max numeric(12, 2) not null check (list_price_max >= list_price),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  color_names text[] not null default '{}',
  primary_colors text[] not null default '{}',
  season_codes text[] not null default '{}',
  source_name text not null,
  source_url text not null,
  source_hash text not null check (source_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'active'
    check (status in ('active', 'missing', 'inactive')),
  missing_runs integer not null default 0 check (missing_runs >= 0),
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  last_changed_at timestamptz not null,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  unique (brand_key, official_product_id),
  check (catalog_product_id = brand_key || ':' || pg_catalog.lower(official_product_id)),
  check (
    (brand_key = 'arcteryx' and brand = 'Arc''teryx' and country = 'us' and currency = 'USD')
    or (brand_key = 'burton' and brand = 'Burton' and country = 'us' and currency = 'USD')
    or (brand_key = 'patagonia' and brand = 'Patagonia' and country = 'au' and currency = 'AUD')
  ),
  check (
    (brand_key = 'arcteryx' and source_name = 'arcteryx_us_official_product_feed'
      and source_url ~ '^https://arcteryx[.]com/us/en/shop/')
    or (brand_key = 'burton' and source_name = 'burton_us_official_collection_json'
      and source_url ~ '^https://www[.]burton[.]com/en-us/products/')
    or (brand_key = 'patagonia' and source_name = 'patagonia_au_official_collection_json'
      and source_url ~ '^https://www[.]patagonia[.]com[.]au/products/')
  ),
  check (last_seen_at >= first_seen_at),
  check (last_changed_at >= first_seen_at)
);

create index if not exists catalog_products_brand_status_idx
  on public.catalog_products (brand_key, status, last_seen_at desc);
create index if not exists catalog_products_gender_idx
  on public.catalog_products (gender);
create index if not exists catalog_products_categories_idx
  on public.catalog_products using gin (categories);
create index if not exists catalog_products_season_codes_idx
  on public.catalog_products using gin (season_codes);

create table if not exists public.catalog_product_snapshots (
  id bigint generated by default as identity primary key,
  catalog_product_id text not null
    references public.catalog_products (catalog_product_id) on delete restrict,
  brand_key text not null
    check (brand_key in ('arcteryx', 'burton', 'patagonia')),
  official_product_id text not null
    check (official_product_id ~ '^[0-9A-Z][0-9A-Z._-]{1,63}$'),
  brand text not null,
  catalog_scope text not null check (catalog_scope = 'full_price'),
  market text not null check (pg_catalog.btrim(market) <> ''),
  country text not null check (country ~ '^[a-z]{2}$'),
  language text not null check (language = 'en'),
  name text not null check (pg_catalog.btrim(name) <> ''),
  gender text not null check (gender in ('men', 'women', 'kids', 'unisex')),
  collection text,
  categories text[] not null default '{}',
  category_sources jsonb not null default '{}'
    check (pg_catalog.jsonb_typeof(category_sources) = 'object'),
  list_price numeric(12, 2) not null check (list_price >= 0),
  list_price_max numeric(12, 2) not null check (list_price_max >= list_price),
  currency text not null check (currency ~ '^[A-Z]{3}$'),
  color_names text[] not null default '{}',
  primary_colors text[] not null default '{}',
  season_codes text[] not null default '{}',
  source_name text not null,
  source_url text not null,
  source_hash text not null check (source_hash ~ '^[0-9a-f]{64}$'),
  observed_at timestamptz not null,
  created_at timestamptz not null default pg_catalog.now(),
  unique (catalog_product_id, source_hash),
  check (catalog_product_id = brand_key || ':' || pg_catalog.lower(official_product_id)),
  check (
    (brand_key = 'arcteryx' and brand = 'Arc''teryx'
      and source_url ~ '^https://arcteryx[.]com/us/en/shop/')
    or (brand_key = 'burton' and brand = 'Burton'
      and source_url ~ '^https://www[.]burton[.]com/en-us/products/')
    or (brand_key = 'patagonia' and brand = 'Patagonia'
      and source_url ~ '^https://www[.]patagonia[.]com[.]au/products/')
  )
);

create index if not exists catalog_product_snapshots_product_observed_idx
  on public.catalog_product_snapshots (catalog_product_id, observed_at desc);
create index if not exists catalog_product_snapshots_observed_idx
  on public.catalog_product_snapshots (observed_at desc);

alter table public.catalog_products enable row level security;
alter table public.catalog_product_snapshots enable row level security;

drop policy if exists catalog_public_read_active on public.catalog_products;
create policy catalog_public_read_active
  on public.catalog_products for select
  to anon, authenticated
  using (status = 'active');

drop policy if exists catalog_public_read_snapshots on public.catalog_product_snapshots;
create policy catalog_public_read_snapshots
  on public.catalog_product_snapshots for select
  to anon, authenticated
  using (true);

revoke all on table public.catalog_products from public, anon, authenticated;
revoke all on table public.catalog_product_snapshots from public, anon, authenticated;
grant select on table public.catalog_products to anon, authenticated;
grant select on table public.catalog_product_snapshots to anon, authenticated;
grant select, insert, update, delete on table public.catalog_products to service_role;
grant select, insert on table public.catalog_product_snapshots to service_role;
grant usage, select on sequence public.catalog_product_snapshots_id_seq to service_role;
